name: Build WASM frontend

on:
  pull_request:

  push:
    tags:
      - 'v*'

  workflow_dispatch:
    inputs:
      version:
        description: 'Version number in the format `v1.2.3`'
        required: true
        type: string

jobs:
  build-wasm:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: 'examples'

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install wasm-bindgen-cli
        run: |
          cargo install wasm-bindgen-cli

      - name: Cargo build (for wasm)
        run: |
          rustup target add wasm32-unknown-unknown
          cd examples
          ./build_wasm.sh
          
      - name: Prepare Dockerfile
        run: |
          echo '
          FROM nginx:mainline-alpine
          COPY ./htdocs/* /usr/share/nginx/html/
          ' > Dockerfile.generated

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ github.repository }}-wasm
          tags: |
            type=semver,pattern={{version}}
            type=sha,format=long
            latest

      - name:  Build and publish a Docker image for ${{ github.repository }}
        uses: docker/build-push-action@v6
        with:
          push: true
          context: .
          file: ./Dockerfile.generated
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
